# Application settings
base.url=https://www.saucedemo.com/
browser=chrome
headless=false
implicit.wait.seconds=5
explicit.wait.seconds=10
page.load.timeout.seconds=30

# Screenshot / report 
screenshot.dir=test-output/screenshots
report.dir=test-output/extent-report
